export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const GET_STUDENT_APPROVAL_REQUEST = "GET_STUDENT_APPROVAL_REQUEST";
export const GET_STUDENT_APPROVAL_SUCCESS = "GET_STUDENT_APPROVAL_SUCCESS";
export const GET_STUDENT_APPROVAL_FAIL = "GET_STUDENT_APPROVAL_FAIL";

export const STUDENT_APPROVAL_ACCEPT_REQUEST =
  "STUDENT_APPROVAL_ACCEPT_REQUEST";
export const STUDENT_APPROVAL_ACCEPT_SUCCESS =
  "STUDENT_APPROVAL_ACCEPT_SUCCESS";
export const STUDENT_APPROVAL_ACCEPT_FAIL = "STUDENT_APPROVAL_ACCEPT_FAIL";

export const STUDENT_APPROVAL_REJECT_REQUEST =
  "STUDENT_APPROVAL_REJECT_REQUEST";
export const STUDENT_APPROVAL_REJECT_SUCCESS =
  "STUDENT_APPROVAL_REJECT_SUCCESS";
export const STUDENT_APPROVAL_REJECT_FAIL = "STUDENT_APPROVAL_REJECT_FAIL";

export const REGISTER_TEACHER_REQUEST = "REGISTER_TEACHER_REQUEST";
export const REGISTER_TEACHER_SUCCESS = "REGISTER_TEACHER_SUCCESS";
export const REGISTER_TEACHER_FAIL = "REGISTER_TEACHER_FAIL";

export const GET_TEACHER_APPROVAL_REQUEST = "GET_TEACHER_APPROVAL_REQUEST";
export const GET_TEACHER_APPROVAL_SUCCESS = "GET_TEACHER_APPROVAL_SUCCESS";
export const GET_TEACHER_APPROVAL_FAIL = "GET_TEACHER_APPROVAL_FAIL";

export const TEACHER_APPROVAL_ACCEPT_REQUEST =
  "TEACHER_APPROVAL_ACCEPT_REQUEST";
export const TEACHER_APPROVAL_ACCEPT_SUCCESS =
  "TEACHER_APPROVAL_ACCEPT_SUCCESS";
export const TEACHER_APPROVAL_ACCEPT_FAIL = "TEACHER_APPROVAL_ACCEPT_FAIL";

export const TEACHER_APPROVAL_REJECT_REQUEST =
  "TEACHER_APPROVAL_REJECT_REQUEST";
export const TEACHER_APPROVAL_REJECT_SUCCESS =
  "TEACHER_APPROVAL_REJECT_SUCCESS";
export const TEACHER_APPROVAL_REJECT_FAIL = "TEACHER_APPROVAL_REJECT_FAIL";

export const UPDATE_TEACHER_ROLE_REQUEST = "UPDATE_TEACHER_ROLE_REQUEST";
export const UPDATE_TEACHER_ROLE_SUCCESS = "UPDATE_TEACHER_ROLE_SUCCESS";
export const UPDATE_TEACHER_ROLE_FAIL = "UPDATE_TEACHER_ROLE_FAIL";

export const GET_ALL_TEACHER_REQUEST = "GET_ALL_TEACHER_REQUEST";
export const GET_ALL_TEACHER_SUCCESS = "GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FAIL = "GET_ALL_TEACHER_FAIL";

export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAIL = "GET_ALL_STUDENTS_FAIL";

export const REMOVE_TEACHER_REQUEST = "REMOVE_TEACHER_REQUEST";
export const REMOVE_TEACHER_SUCCESS = "REMOVE_TEACHER_SUCCESS";
export const REMOVE_TEACHER_FAIL = "REMOVE_TEACHER_FAIL";

export const REMOVE_STUDENT_REQUEST = "REMOVE_STUDENT_REQUEST";
export const REMOVE_STUDENT_SUCCESS = "REMOVE_STUDENT_SUCCESS";
export const REMOVE_STUDENT_FAIL = "REMOVE_STUDENT_FAIL";

export const UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_REQUEST =
  "UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_REQUEST";
export const UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_SUCCESS =
  "UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_SUCCESS";
export const UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_FAIL =
  "UPDATE_STUDENT_DATA_BY_DEAN_OR_HOD_FAIL";

export const UPDATE_TEACHER_DATA_BY_DEAN_REQUEST =
  "UPDATE_TEACHER_DATA_BY_DEAN_REQUEST";
export const UPDATE_TEACHER_DATA_BY_DEAN_SUCCESS =
  "UPDATE_TEACHER_DATA_BY_DEAN_SUCCESS";
export const UPDATE_TEACHER_DATA_BY_DEAN_FAIL =
  "UPDATE_TEACHER_DATA_BY_DEAN_FAIL";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
