export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

export const CREATE_SUBJECT_REQUEST = "CREATE_SUBJECT_REQUEST";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_FAIL = "CREATE_SUBJECT_FAIL";

export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_FAIL = "GET_SUBJECT_FAIL";

export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAIL = "GET_COURSE_FAIL";

export const UPDATE_SUBJECT_ASSIGNED_REQUEST =
  "UPDATE_SUBJECT_ASSIGNED_REQUEST";
export const UPDATE_SUBJECT_ASSIGNED_SUCCESS =
  "UPDATE_SUBJECT_ASSIGNED_SUCCESS";
export const UPDATE_SUBJECT_ASSIGNED_FAIL = "UPDATE_SUBJECT_ASSIGNED_FAIL";

export const GET_SESSION_LIST_REQUEST = "GET_SESSION_LIST_REQUEST";
export const GET_SESSION_LIST_SUCCESS = "GET_SESSION_LIST_SUCCESS";
export const GET_SESSION_LIST_FAIL = "GET_SESSION_LIST_FAIL";

export const PROMOTE_STUDENT_REQUEST = "PROMOTE_STUDENT_REQUEST";
export const PROMOTE_STUDENT_SUCCESS = "PROMOTE_STUDENT_SUCCESS";
export const PROMOTE_STUDENT_FAIL = "PROMOTE_STUDENT_FAIL";

export const DETENTION_STUDENT_REQUEST = "DETENTION_STUDENT_REQUEST";
export const DETENTION_STUDENT_SUCCESS = "DETENTION_STUDENT_SUCCESS";
export const DETENTION_STUDENT_FAIL = "DETENTION_STUDENT_FAIL";
